---

_You are currently looking at **version 1.5** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-data-analysis/resources/0dhYG) course resource._

---

# Assignment 3 - More Pandas
This assignment requires more individual learning then the last one did - you are encouraged to check out the [pandas documentation](http://pandas.pydata.org/pandas-docs/stable/) to find functions or methods you might not have used yet, or ask questions on [Stack Overflow](http://stackoverflow.com/) and tag them as pandas and python related. And of course, the discussion forums are open for interaction with your peers and the course staff.

### Question 1 (20%)
Load the energy data from the file `Energy Indicators.xls`, which is a list of indicators of [energy supply and renewable electricity production](Energy%20Indicators.xls) from the [United Nations](http://unstats.un.org/unsd/environment/excel_file_tables/2013/Energy%20Indicators.xls) for the year 2013, and should be put into a DataFrame with the variable name of **energy**.

Keep in mind that this is an Excel file, and not a comma separated values file. Also, make sure to exclude the footer and header information from the datafile. The first two columns are unneccessary, so you should get rid of them, and you should change the column labels so that the columns are:

`['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']`

Convert `Energy Supply` to gigajoules (there are 1,000,000 gigajoules in a petajoule). For all countries which have missing data (e.g. data with "...") make sure this is reflected as `np.NaN` values.

Rename the following list of countries (for use in later questions):

```"Republic of Korea": "South Korea",
"United States of America": "United States",
"United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
"China, Hong Kong Special Administrative Region": "Hong Kong"```

There are also several countries with numbers and/or parenthesis in their name. Be sure to remove these, 

e.g. 

`'Bolivia (Plurinational State of)'` should be `'Bolivia'`, 

`'Switzerland17'` should be `'Switzerland'`.

<br>

Next, load the GDP data from the file `world_bank.csv`, which is a csv containing countries' GDP from 1960 to 2015 from [World Bank](http://data.worldbank.org/indicator/NY.GDP.MKTP.CD). Call this DataFrame **GDP**. 

Make sure to skip the header, and rename the following list of countries:

```"Korea, Rep.": "South Korea", 
"Iran, Islamic Rep.": "Iran",
"Hong Kong SAR, China": "Hong Kong"```

<br>

Finally, load the [Sciamgo Journal and Country Rank data for Energy Engineering and Power Technology](http://www.scimagojr.com/countryrank.php?category=2102) from the file `scimagojr-3.xlsx`, which ranks countries based on their journal contributions in the aforementioned area. Call this DataFrame **ScimEn**.

Join the three datasets: GDP, Energy, and ScimEn into a new dataset (using the intersection of country names). Use only the last 10 years (2006-2015) of GDP data and only the top 15 countries by Scimagojr 'Rank' (Rank 1 through 15). 

The index of this DataFrame should be the name of the country, and the columns should be ['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations',
       'Citations per document', 'H index', 'Energy Supply',
       'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015'].

*This function should return a DataFrame with 20 columns and 15 entries.*

In [1]:
import pandas as pd
import numpy as np
def answer_one():

    GDP=pd.read_csv("world_bank.csv",skiprows=4)
    
    GDP=GDP[["Country Name","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015"]]
    GDP=GDP.replace({"Korea, Rep.": "South Korea", 
        "Iran, Islamic Rep.": "Iran",
        "Hong Kong SAR, China": "Hong Kong"})
    GDP=GDP.set_index("Country Name")
    # ---------------------------------------------------
    ENERGY=pd.read_excel("Energy Indicators.xls",skiprows=16,na_values=["..."])
    ENERGY=ENERGY.drop(["Unnamed: 0","Unnamed: 1"],axis=1)
    
    ENERGY=ENERGY.drop(ENERGY.index[0],axis=0)
    
    ENERGY=ENERGY.drop(ENERGY.index[227:])

    ENERGY=ENERGY.rename(columns={"Unnamed: 2":"Country","Energy Supply per capita":"Energy Supply per Capita","Renewable Electricity Production":"% Renewable"})
    
    ENERGY["Energy Supply"]=ENERGY["Energy Supply"]*1000000
    f="("
    for i in ENERGY["Country"]:
    #         print(i,s)

        contains_digit = any(map(str.isdigit, i))

        if contains_digit:
            numbers = sum(c.isdigit() for c in i)

            ENERGY=ENERGY.replace({i:i[:len(i)-numbers]})
#             print("if")
#             print("-----------------")
    #         elif f[1] in list(s):
    #             ENERGY=ENERGY.rename({ENERGY.index[i]:ENERGY.index[i].split(",")[0].strip()})
    #     #         print("elif1",ENERGY.index[i].split(",")[0].strip())
    #     #         print("-----------------")



        elif f in list(i):
            ENERGY=ENERGY.replace({i:i.split("(")[0].strip()})
#             print("elif2",i)
#             print("-----------------")
#     print(ENERGY.loc["United Kingdom"])
    ENERGY=ENERGY.replace({"Republic of Korea": "South Korea","United States of America": "United States",
    "United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
    "China, Hong Kong Special Administrative Region": "Hong Kong","Virgin Islands (U.S.)":"United States Virgin Island"})
    ENERGY=ENERGY.set_index("Country")
    # ---------------------------------------------------
    ScimEn=pd.read_excel("scimagojr-3.xlsx")
    #     ScimEn=ScimEn.iloc[:15,:]
    
    ScimEn=ScimEn.set_index("Country")
    d1=ScimEn.nsmallest(15,"Rank")
    d=ENERGY.merge(GDP, how='inner', left_index=True, right_index=True).merge(ScimEn, how='inner', left_index=True, right_index=True)
    d=d.sort_values(by=["Rank"])[:15]
#     new_d=d
#     new_d["% Renewable"]=new_d["% Renewable"].fillna(np.nan)
#     new_d["Energy Supply"]=new_d["Energy Supply"].fillna(np.nan)
#     new_d["Energy Supply per Capita"]=new_d["Energy Supply per Capita"].fillna(np.nan)
#     print(len(GDP),len(ENERGY),len(ScimEn))
    
    return d

answer_one()


# GDP=pd.read_csv("world_bank.csv",skiprows=4)
# GDP=GDP[["Country Name","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015"]]
# GDP=GDP.set_index("Country Name")

# # ---------------------------------------------------
# ENERGY=pd.read_excel("Energy Indicators.xls",skiprows=16,na_values=["..."])
# ENERGY=ENERGY.drop(["Unnamed: 0","Unnamed: 1"],axis=1)
# ENERGY=ENERGY.drop(ENERGY.index[228:])

# ENERGY=ENERGY.rename(columns={"Unnamed: 2":"Country","Energy Supply per capita":"Energy Supply per Capita","Renewable Electricity Production":"% Renewable"})
# ENERGY=ENERGY.replace({"Republic of Korea": "South Korea","United States of America": "United States",
# "United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
# "China, Hong Kong Special Administrative Region": "Hong Kong"})
# ENERGY=ENERGY.drop(ENERGY.index[0],axis=0)
# ENERGY=ENERGY.set_index("Country")
# ENERGY["Energy Supply"]=ENERGY["Energy Supply"]*1000000
# print(ENERGY.index)
# # ---------------------------------------------------
# ScimEn=pd.read_excel("scimagojr-3.xlsx")
# #     ScimEn=ScimEn.iloc[:15,:]
# ScimEn=ScimEn.set_index("Country")
# d=pd.merge(ScimEn, ENERGY, how='left', left_index=True, right_index=True)
# #     print(d.head(30))
# d=pd.merge( d,GDP, how='left', left_index=True, right_index=True)
# d=d.sort_values(by=["Rank"])
# new_d=d.nsmallest(15,"Rank")
# new_d["% Renewable"]=new_d["% Renewable"].fillna(np.nan)
# new_d["Energy Supply"]=new_d["Energy Supply"].fillna(np.nan)
# new_d["Energy Supply per Capita"]=new_d["Energy Supply per Capita"].fillna(np.nan)

# n=['0','1','2','3','4','5','6','7','8','9']
# f=["(",")",","]
# for i in range(len(ENERGY.index)):
#     s=ENERGY.index[i]
#     print(i,s)
#     contains_digit = any(map(str.isdigit, s))

#     if contains_digit:
#         ENERGY=ENERGY.rename({ENERGY.index[i]:s[:len(s)-2]})
# #         print("if",ENERGY.index[i])
# #         print("-----------------")
#     elif f[2] in list(s):
#         ENERGY=ENERGY.rename({ENERGY.index[i]:ENERGY.index[i].split(",")[0].strip()})
# #         print("elif1",ENERGY.index[i].split(",")[0].strip())
# #         print("-----------------")
        

#     elif f[0] in list(s):
#         ENERGY=ENERGY.rename({ENERGY.index[i]:ENERGY.index[i].split("(")[0].strip()})
# #         print("elif2",ENERGY.index[i])
#         print("-----------------")
        
# import pandas as pd
# import numpy as np
# def answer_one1():
#     energy = pd.read_excel('Energy Indicators.xls')
#     print(energy.head(20))
#     energy=energy.drop(['Unnamed: 0','Unnamed: 1'],axis=1)[16:243]
#     energy.columns = ['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']
#     energy.replace('...',np.nan,inplace=True)
#     energy['Energy Supply']*=1000000
#     def remove_digit(data):
#             newData = ''.join([i for i in data if not i.isdigit()])
#             i = newData.find('(')
#             if i>-1: newData = newData[:i]
#             return newData.strip()
#     energy['Country']=energy['Country'].apply(remove_digit)
#     energy['Country']=energy['Country'].replace(['Republic of Korea','United States of America','United Kingdom of Great Britain and Northern Ireland','China, Hong Kong Special Administrative Region','Bolivia (Plurinational State of)','Switzerland17'],['South Korea','United States','United Kingdom','Hong Kong','Bolivia','Switzerland'])

#     GDP=pd.read_csv('world_bank.csv',skiprows=4)
#     GDP.rename(columns={'Country Name':'Country'},inplace=True)
#     GDP['Country']=GDP['Country'].replace(["Korea, Rep.","Iran, Islamic Rep.","Hong Kong SAR, China"],["South Korea","Iran","Hong Kong"])

#     ScimEn=pd.read_excel('scimagojr-3.xlsx')[:15]

#     df=energy.merge(GDP,how='inner',on='Country').merge(ScimEn,how='inner',on='Country')
#     df.set_index('Country',inplace=True)
#     df=df[['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations', 'Citations per document', 'H index', 'Energy Supply', 'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']]
#     df.sort_values(by='Rank',inplace=True)
#     return df
# answer_one1()

,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index
China,1.271910e+11,93.0,19.754910,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,1,127050,126767,597237,411683,4.70,138
United States,9.083800e+10,286.0,11.570980,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13,2,96661,94747,792274,265436,8.20,230
Japan,1.898400e+10,149.0,10.232820,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,3,30504,30287,223024,61554,7.31,134
United Kingdom,7.920000e+09,124.0,10.600470,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12,4,20944,20357,206091,37874,9.84,139
Russian Federation,3.070900e+10,214.0,17.288680,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12,5,18534,18301,34266,12422,1.85,57
Canada,1.043100e+10,296.0,61.945430,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12,6,17899,17620,215003,40930,12.01,149
Germany,1.326100e+10,165.0,17.901530,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12,7,17027,16831,140566,27426,8.26,126
India,3.319500e+10,26.0,14.969080,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12,8,15005,14841,128763,37209,8.58,115
France,1.059700e+10,166.0,17.020280,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12,9,13153,12973,130632,28601,9.93,114
South Korea,1.100700e+10,221.0,2.279353,9.410199e+11,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12,10,11983,11923,114675,22595,9.57,104
Italy,6.530000e+09,109.0,33.667230,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12,11,10964,10794,111850,26661,10.20,106
Spain,4.923000e+09,106.0,37.968590,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12,12,9428,9330,123336,23964,13.08,115
Iran,9.172000e+09,119.0,5.707721,3.895523e+11,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN,13,8896,8819,57470,19125,6.46,72
Australia,5.386000e+09,231.0,11.810810,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12,14,8831,8725,90765,15606,10.28,107
Brazil,1.214900e+10,59.0,69.648030,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12,15,8668,8596,60702,14396,7.00,86

### Question 2 (6.6%)
The previous question joined three datasets then reduced this to just the top 15 entries. When you joined the datasets, but before you reduced this to the top 15 items, how many entries did you lose?

*This function should return a single number.*

In [2]:


%%HTML
<svg width="800" height="300">
  <circle cx="150" cy="180" r="80" fill-opacity="0.2" stroke="black" stroke-width="2" fill="blue" />
  <circle cx="200" cy="100" r="80" fill-opacity="0.2" stroke="black" stroke-width="2" fill="red" />
  <circle cx="100" cy="100" r="80" fill-opacity="0.2" stroke="black" stroke-width="2" fill="green" />
  <line x1="150" y1="125" x2="300" y2="150" stroke="black" stroke-width="2" fill="black" stroke-dasharray="5,3"/>
  <text  x="300" y="165" font-family="Verdana" font-size="35">Everything but this!</text>
</svg>

In [3]:
def answer_two():
    GDP=pd.read_csv("world_bank.csv",skiprows=4)
    
    GDP=GDP[["Country Name","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015"]]
    GDP=pd.read_csv("world_bank.csv",skiprows=4)
    
    GDP=GDP[["Country Name","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015"]]
    GDP=GDP.replace({"Korea, Rep.": "South Korea", 
        "Iran, Islamic Rep.": "Iran",
        "Hong Kong SAR, China": "Hong Kong"})
    GDP=GDP.set_index("Country Name")
    # ---------------------------------------------------
    ENERGY=pd.read_excel("Energy Indicators.xls",skiprows=16,na_values=["..."])
    ENERGY=ENERGY.drop(["Unnamed: 0","Unnamed: 1"],axis=1)
    ENERGY=ENERGY.drop(ENERGY.index[0],axis=0)
    
    ENERGY=ENERGY.drop(ENERGY.index[227:])

    ENERGY=ENERGY.rename(columns={"Unnamed: 2":"Country","Energy Supply per capita":"Energy Supply per Capita","Renewable Electricity Production":"% Renewable"})
    
    ENERGY["Energy Supply"]=ENERGY["Energy Supply"]*1000000
    f="("
    for i in ENERGY["Country"]:
    #         print(i,s)
    

        contains_digit = any(map(str.isdigit, i))

        if contains_digit:
            numbers = sum(c.isdigit() for c in i)

            ENERGY=ENERGY.replace({i:i[:len(i)-numbers]})
    #         print("if",ENERGY.index[i])
    #         print("-----------------")
    #         elif f[1] in list(s):
    #             ENERGY=ENERGY.rename({ENERGY.index[i]:ENERGY.index[i].split(",")[0].strip()})
    #     #         print("elif1",ENERGY.index[i].split(",")[0].strip())
    #     #         print("-----------------")



        elif f in list(i):
            ENERGY=ENERGY.replace({i:i.split("(")[0].strip()})
    #         print("elif2",ENERGY.index[i])
    #         print("-----------------")
#     print(ENERGY.loc["United Kingdom"])

    def remove_digit(data):
        newData = ''.join([i for i in data if not i.isdigit()])
        i = newData.find('(')
        if i>-1: newData = newData[:i]
        return newData.strip()
    ENERGY=ENERGY.replace({"Republic of Korea": "South Korea","United States of America": "United States",
    "United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
    "China, Hong Kong Special Administrative Region": "Hong Kong"})
    ENERGY=ENERGY.set_index("Country")
    # ---------------------------------------------------
    ScimEn=pd.read_excel("scimagojr-3.xlsx")
    #     ScimEn=ScimEn.iloc[:15,:]
    
    ScimEn=ScimEn.set_index("Country")
#     d=pd.merge(ScimEn, ENERGY, how='left', left_index=True, right_index=True)
#     #     print(d.head(30))
#     d=pd.merge( d,GDP, how='left', left_index=True, right_index=True)
#     d=d.sort_values(by=["Rank"])
#     new_d=d.nsmallest(15,"Rank")
#     new_d["% Renewable"]=new_d["% Renewable"].fillna(np.nan)
#     new_d["Energy Supply"]=new_d["Energy Supply"].fillna(np.nan)
#     new_d["Energy Supply per Capita"]=new_d["Energy Supply per Capita"].fillna(np.nan)

    
    #     d.head(30)
#     print(len(ENERGY)-len(d),len(ScimEn)-len(d))
    
#     print(len(GDP),len(ENERGY),len(ScimEn))

#     d=d.sort_values(by=["Rank"])
#     new_d=d.nsmallest(15,"Rank")
#     df=energy.merge(GDP,how='inner',on='Country').merge(ScimEn,how='inner',on='Country')

    d_in=ENERGY.merge(GDP, how='inner', left_index=True, right_index=True).merge(ScimEn, how='inner', left_index=True, right_index=True)
    #     print(d.head(30))
#     d=pd.merge( d,GDP, how='left', left_index=True, right_index=True)
    d_out=ENERGY.merge(GDP, how='outer', left_index=True, right_index=True).merge(ScimEn, how='outer', left_index=True, right_index=True)

    do=pd.merge(ScimEn, ENERGY, how='outer', left_index=True, right_index=True)
    do=pd.merge(do, GDP, how='outer', left_index=True, right_index=True)
#     d_out=len(do)
#     print(len(GDP),len(ENERGY),len(ScimEn))
    return len(d_out)-len(d_in)
answer_two()
# GDP.shape[0]+ENERGY.shape[0]+ScimEn.shape[0]-3*d.shape[0]
# print(GDP.shape,ENERGY.shape,ScimEn.shape)



# def answer_two1():
#     energy = pd.read_excel('Energy Indicators.xls').drop(['Unnamed: 0','Unnamed: 1'],axis=1)[16:]
#     energy.columns = ['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']
#     energy=energy.drop(energy.index[0],axis=0)
#     energy=energy.drop(energy.index[227:])
    
#     print(energy.head(230))
    
#     energy.replace('...',np.nan,inplace=True)
#     energy['Energy Supply']*=1000000
#     def remove_digit(data):
#             newData = ''.join([i for i in data if not i.isdigit()])
#             i = newData.find('(')
#             if i>-1: newData = newData[:i]
#             return newData.strip()
#     energy['Country']=energy['Country'].apply(remove_digit)
#     energy['Country']=energy['Country'].replace(['Republic of Korea','United States of America','United Kingdom of Great Britain and Northern Ireland','China, Hong Kong Special Administrative Region','Bolivia (Plurinational State of)','Switzerland17'],['South Korea','United States','United Kingdom','Hong Kong','Bolivia','Switzerland'])

#     GDP=pd.read_csv('world_bank.csv',skiprows=4)
#     GDP.rename(columns={'Country Name':'Country'},inplace=True)
#     GDP['Country']=GDP['Country'].replace(["Korea, Rep.","Iran, Islamic Rep.","Hong Kong SAR, China"],["South Korea","Iran","Hong Kong"])

#     ScimEn=pd.read_excel('scimagojr-3.xlsx')
# #     Sco=pd.read_excel('scimagojr-3.xlsx')

#     df=energy.merge(GDP,how='outer',on='Country').merge(ScimEn,how='outer',on='Country')
#     df1=energy.merge(GDP,how='inner',on='Country').merge(ScimEn,how='inner',on='Country')
#     return df.shape[0]-df1.shape[0]
# answer_two1()

156

## Answer the following questions in the context of only the top 15 countries by Scimagojr Rank (aka the DataFrame returned by `answer_one()`)

### Question 3 (6.6%)
What is the average GDP over the last 10 years for each country? (exclude missing values from this calculation.)

*This function should return a Series named `avgGDP` with 15 countries and their average GDP sorted in descending order.*

In [4]:
import numpy as np
def answer_three():
    Top15 = answer_one()
#     Top15=Top15.fillna(0)
    data=["2006","2007","2008","2009","2010","2011","2012","2013","2014","2015"]
    s=Top15.apply(lambda x:np.average(x[data]),axis=1).sort_values(ascending=False)
    return s
answer_three()

United States         1.536434e+13
China                 6.348609e+12
Japan                 5.542208e+12
Germany               3.493025e+12
France                2.681725e+12
United Kingdom        2.487907e+12
Brazil                2.189794e+12
Italy                 2.120175e+12
India                 1.769297e+12
Canada                1.660647e+12
Russian Federation    1.565459e+12
Spain                 1.418078e+12
Australia             1.164043e+12
South Korea           1.106715e+12
Iran                           NaN
dtype: float64

### Question 4 (6.6%)
By how much had the GDP changed over the 10 year span for the country with the 6th largest average GDP?

*This function should return a single number.*

In [5]:
def answer_four():
    Top15 = answer_one()
    data=["2006","2007","2008","2009","2010","2011","2012","2013","2014","2015"]
    s=Top15.apply(lambda x:np.average(x[data]),axis=1).sort_values(ascending=False)
    # print(s.index[5])
    # Top15.loc[s.index[5]].iloc[10:].max()-Top15.loc[s.index[5]].iloc[10:].min()
    # Top15["United Kingdom"]
    # print(Top15.loc[s.index[5]].iloc[10:].max(),Top15.loc[s.index[5]].iloc[10:].min())
    return Top15.loc[s.index[5]]["2015"]-Top15.loc[s.index[5]]["2006"]

answer_four()

246702696075.3999

### Question 5 (6.6%)
What is the mean `Energy Supply per Capita`?

*This function should return a single number.*

In [6]:
def answer_five():
    Top15 = answer_one()
    Top15.fillna(0)
    return np.mean(Top15["Energy Supply per Capita"].astype(float))
answer_five()

157.6

### Question 6 (6.6%)
What country has the maximum % Renewable and what is the percentage?

*This function should return a tuple with the name of the country and the percentage.*

In [7]:
def answer_six():
    Top15 = answer_one()
    i=Top15.index[Top15["% Renewable"]==Top15["% Renewable"].max()]
    return (i[0],Top15.loc[i]["% Renewable"][0])
answer_six()

('Brazil', 69.64803)

### Question 7 (6.6%)
Create a new column that is the ratio of Self-Citations to Total Citations. 
What is the maximum value for this new column, and what country has the highest ratio?

*This function should return a tuple with the name of the country and the ratio.*

In [8]:
def answer_seven():
    Top15 = answer_one()
    Top15["rate"]=Top15["Self-citations"]/Top15["Citations"]
    i=Top15.index[Top15["rate"]==Top15["rate"].max()]
    
    return (i[0],Top15.loc[i]["rate"][0])
answer_seven()

('China', 0.6893126179389422)

### Question 8 (6.6%)

Create a column that estimates the population using Energy Supply and Energy Supply per capita. 
What is the third most populous country according to this estimate?

*This function should return a single string value.*

In [9]:
def answer_eight():
    Top15 = answer_one()
#     Top15 = answer_one()
    Top15["rate"]=Top15["Energy Supply"]/Top15["Energy Supply per Capita"]
    i=Top15.index[Top15["rate"]==Top15["rate"].max()]
    Top15=Top15.sort_values("rate",ascending=False)
    return Top15.index[2]
answer_eight()

'United States'

### Question 9 (6.6%)
Create a column that estimates the number of citable documents per person. 
What is the correlation between the number of citable documents per capita and the energy supply per capita? Use the `.corr()` method, (Pearson's correlation).

*This function should return a single number.*

*(Optional: Use the built-in function `plot9()` to visualize the relationship between Energy Supply per Capita vs. Citable docs per Capita)*

In [10]:
def answer_nine():
    Top15 = answer_one()
    Top15['PopEst'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    Top15['Citable docs per Capita'] = Top15['Citable documents'] / Top15['PopEst']
    Top15=Top15[["Citable docs per Capita","Energy Supply per Capita"]]
    return Top15.corr(method="pearson")["Citable docs per Capita"]["Energy Supply per Capita"]
    
    
answer_nine()

0.7940010435442943

In [11]:
def plot9():
    import matplotlib as plt
    %matplotlib inline
    
    Top15 = answer_one()
    Top15['PopEst'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    Top15['Citable docs per Capita'] = Top15['Citable documents'] / Top15['PopEst']
    Top15.corr(method=histogram_intersection)
    Top15.plot(x='Citable docs per Capita', y='Energy Supply per Capita', kind='scatter', xlim=[0, 0.0006])

In [12]:
# plot9() # Be sure to comment out plot9() before submitting the assignment!

### Question 10 (6.6%)
Create a new column with a 1 if the country's % Renewable value is at or above the median for all countries in the top 15, and a 0 if the country's % Renewable value is below the median.

*This function should return a series named `HighRenew` whose index is the country name sorted in ascending order of rank.*

In [13]:
def answer_ten():
    Top15 = answer_one()
    m=Top15["% Renewable"].median()
    Top15["HighRenew"]=Top15["% Renewable"].apply(lambda x:1 if x>=m else 0)
    return Top15["HighRenew"]
answer_ten()

China                 1
United States         0
Japan                 0
United Kingdom        0
Russian Federation    1
Canada                1
Germany               1
India                 0
France                1
South Korea           0
Italy                 1
Spain                 1
Iran                  0
Australia             0
Brazil                1
Name: HighRenew, dtype: int64

### Question 11 (6.6%)
Use the following dictionary to group the Countries by Continent, then create a dateframe that displays the sample size (the number of countries in each continent bin), and the sum, mean, and std deviation for the estimated population of each country.

```python
ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}
```

*This function should return a DataFrame with index named Continent `['Asia', 'Australia', 'Europe', 'North America', 'South America']` and columns `['size', 'sum', 'mean', 'std']`*

In [14]:
ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}

def answer_eleven():
    Top15 = answer_one()
    Top15['PopEst'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    Top15["Country"]=Top15.index
    Top15=Top15.reset_index(drop=True)
    
#     Top15["cont"]=Top15["Country"].apply(lambda x:ContinentDict[x])
#     Top15=Top15[["cont","Country","PopEst"]]
#     Top15=Top15.sort_values("cont")
#     Top15=Top15.set_index(["cont"])
#     Top15=Top15.groupby(level=0)["PopEst"].agg({"size":np.size,"sum":np.sum,"mean":np.mean})
    return Top15
answer_eleven()

,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,...,2015,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,PopEst,Country
0,1.271910e+11,93.0,19.754910,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,...,8.797999e+12,1,127050,126767,597237,411683,4.70,138,1.367645e+09,China
1,9.083800e+10,286.0,11.570980,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,...,1.654857e+13,2,96661,94747,792274,265436,8.20,230,3.176154e+08,United States
2,1.898400e+10,149.0,10.232820,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,...,5.669563e+12,3,30504,30287,223024,61554,7.31,134,1.274094e+08,Japan
3,7.920000e+09,124.0,10.600470,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,...,2.666333e+12,4,20944,20357,206091,37874,9.84,139,6.387097e+07,United Kingdom
4,3.070900e+10,214.0,17.288680,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,...,1.616149e+12,5,18534,18301,34266,12422,1.85,57,1.435000e+08,Russian Federation
5,1.043100e+10,296.0,61.945430,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,...,1.792609e+12,6,17899,17620,215003,40930,12.01,149,3.523986e+07,Canada
6,1.326100e+10,165.0,17.901530,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,...,3.685556e+12,7,17027,16831,140566,27426,8.26,126,8.036970e+07,Germany
7,3.319500e+10,26.0,14.969080,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,...,2.367206e+12,8,15005,14841,128763,37209,8.58,115,1.276731e+09,India
8,1.059700e+10,166.0,17.020280,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,...,2.761185e+12,9,13153,12973,130632,28601,9.93,114,6.383735e+07,France
9,1.100700e+10,221.0,2.279353,9.410199e+11,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,...,1.266580e+12,10,11983,11923,114675,22595,9.57,104,4.980543e+07,South Korea
10,6.530000e+09,109.0,33.667230,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,...,2.049316e+12,11,10964,10794,111850,26661,10.20,106,5.990826e+07,Italy
11,4.923000e+09,106.0,37.968590,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,...,1.419821e+12,12,9428,9330,123336,23964,13.08,115,4.644340e+07,Spain
12,9.172000e+09,119.0,5.707721,3.895523e+11,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,...,NaN,13,8896,8819,57470,19125,6.46,72,7.707563e+07,Iran
13,5.386000e+09,231.0,11.810810,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,...,1.301251e+12,14,8831,8725,90765,15606,10.28,107,2.331602e+07,Australia
14,1.214900e+10,59.0,69.648030,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,...,2.319423e+12,15,8668,8596,60702,14396,7.00,86,2.059153e+08,Brazil

### Question 12 (6.6%)
Cut % Renewable into 5 bins. Group Top15 by the Continent, as well as these new % Renewable bins. How many countries are in each of these groups?

*This function should return a __Series__ with a MultiIndex of `Continent`, then the bins for `% Renewable`. Do not include groups with no countries.*

In [28]:
ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}

def answer_twelve():
    Top15 = answer_one()
    Top15['PopEst'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    Top15["Country"]=Top15.index
    Top15=Top15.reset_index()
    Top15["cont"]=Top15["Country"].apply(lambda x:ContinentDict[x])
#     Top15=Top15[["cont","Country","% Renewable"]]
    Top15["% Renewable"]=pd.cut(Top15['% Renewable'],5)
    Top15=Top15.sort_values("cont")
    Top15=Top15.set_index(["cont","% Renewable"])
    Top15=Top15.groupby(level=(0,1))["Country"].agg({"size":np.size})
    t=pd.Series(Top15["size"],Top15.index)
#     .agg({"size":np.size})
#     t=pd.Series(Top15(level=0))
#     Top15=pd.Series(Top15)
#     Top15=Top15.reset_index()
    return t

### Question 13 (6.6%)
Convert the Population Estimate series to a string with thousands separator (using commas). Do not round the results.

e.g. 317615384.61538464 -> 317,615,384.61538464

*This function should return a Series `PopEst` whose index is the country name and whose values are the population estimate string.*

In [25]:
def answer_thirteen():
    Top15 = answer_one()
    Top15['PopEst'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    pd.set_option('display.float_format',lambda x:'%.3f'%x)
#     Top15["PopEst"]=Top15["PopEst"].apply(lambda x:)

    return Top15
    
answer_thirteen()

def addcoma(x):
    x=str(x)
    x1=x[:x.find(".")]
    x2=x[x.find("."):]
    n=len(x1)//3
    for i in range(len(x1)-3,0,-3):
        x1=x1[:i]+","+x1[i:]
        print(x1)
        
        
        
#     for i in range(n):
#         x1.insert(l-(i*3+1),",")
        
    return x1
answer_thirteen()       
# addcoma(317615384.61538464)

,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,...,2014,2015,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,PopEst
China,127191000000.000,93.000,19.755,3992331462570.890,4559041383517.930,4997775145605.960,5459247267275.140,6039658508485.590,6612490294273.650,7124977970399.610,...,8230120617793.520,8797998940421.279,1,127050,126767,597237,411683,4.700,138,1367645161.290
United States,90838000000.000,286.000,11.571,14792303791800.000,15055395304800.000,15011490541400.000,14594842181900.000,14964372000000.000,15204019634600.000,15542161722300.000,...,16156618476000.000,16548573278300.000,2,96661,94747,792274,265436,8.200,230,317615384.615
Japan,18984000000.000,149.000,10.233,5496541517363.310,5617035943770.730,5558526873313.820,5251308399909.320,5498717815809.770,5473738114222.050,5569101602926.180,...,5642884448582.190,5669563143140.970,3,30504,30287,223024,61554,7.310,134,127409395.973
United Kingdom,7920000000.000,124.000,10.600,2419630700401.730,2482203235475.900,2470614405284.300,2367047611711.990,2403504326328.800,2450911011124.850,2479808627472.190,...,2605643189894.930,2666333396477.130,4,20944,20357,206091,37874,9.840,139,63870967.742
Russian Federation,30709000000.000,214.000,17.289,1385792607182.580,1504071117741.300,1583004071092.110,1459199142720.260,1524917468442.010,1589942641764.290,1645875899596.270,...,1678708855070.860,1616148858033.770,5,18534,18301,34266,12422,1.850,57,143500000.000
Canada,10431000000.000,296.000,61.945,1564468853329.450,1596739898466.320,1612713061250.240,1565144676082.310,1613406134731.120,1664086754804.890,1693132927878.080,...,1773485821199.770,1792608764608.810,6,17899,17620,215003,40930,12.010,149,35239864.865
Germany,13261000000.000,165.000,17.902,3332890754966.890,3441560834437.090,3478809377483.440,3283339933774.830,3417298013245.030,3542371125827.810,3556723774834.440,...,3624386278145.700,3685555907284.770,7,17027,16831,140566,27426,8.260,126,80369696.970
India,33195000000.000,26.000,14.969,1265894322131.090,1374865195244.500,1428360609657.800,1549482541544.700,1708458876829.920,1821872415623.620,1924235460945.250,...,2200616575310.970,2367206118959.060,8,15005,14841,128763,37209,8.580,115,1276730769.231
France,10597000000.000,166.000,17.020,2607839735099.340,2669423841059.600,2674637086092.710,2595966887417.220,2646994701986.750,2702031788079.470,2706968211920.530,...,2729631788079.470,2761185430463.580,9,13153,12973,130632,28601,9.930,114,63837349.398
South Korea,11007000000.000,221.000,2.279,941019882149.125,992431619676.197,1020509638539.710,1027729932849.170,1094499338702.720,1134795571930.640,1160809426196.790,...,1234340240503.490,1266580410309.110,10,11983,11923,114675,22595,9.570,104,49805429.864
Italy,6530000000.000,109.000,33.667,2202169663576.160,2234626814701.990,2211154176556.290,2089937511523.180,2125184794172.190,2137439133774.830,2077184315761.590,...,2033867707549.670,2049315603576.160,11,10964,10794,111850,26661,10.200,106,59908256.881
Spain,4923000000.000,106.000,37.969,1414822516556.290,1468145695364.240,1484529801324.500,1431475496688.740,1431672847682.120,1417354966887.420,1380215894039.730,...,1375605298013.240,1419821192052.980,12,9428,9330,123336,23964,13.080,115,46443396.226
Iran,9172000000.000,119.000,5.708,389552313541.270,425064554419.087,428990857822.095,438920754763.986,467790215915.476,485330901134.448,453256899727.832,...,463902735245.890,nan,13,8896,8819,57470,19125,6.460,72,77075630.252
Australia,5386000000.000,231.000,11.811,1021939264106.670,1060340245233.550,1099643871866.030,1119653852349.080,1142250506474.060,1169431057881.910,1211913217353.490,...,1272519759757.290,1301251030445.660,14,8831,8725,90765,15606,10.280,107,23316017.316
Brazil,12149000000.000,59.000,69.648,1845079664513.560,1957118136056.330,2056809174052.930,2054214562458.190,2208872214643.020,2295244758549.530,2339209222185.090,...,2412230647720.450,2319423390494.130,15,8668,8596,60702,14396,7.000,86,205915254.237

### Optional

Use the built in function `plot_optional()` to see an example visualization.

In [26]:
def plot_optional():
    import matplotlib as plt
    %matplotlib inline
    Top15 = answer_one()
    ax = Top15.plot(x='Rank', y='% Renewable', kind='scatter', 
                    c=['#e41a1c','#377eb8','#e41a1c','#4daf4a','#4daf4a','#377eb8','#4daf4a','#e41a1c',
                       '#4daf4a','#e41a1c','#4daf4a','#4daf4a','#e41a1c','#dede00','#ff7f00'], 
                    xticks=range(1,16), s=6*Top15['2014']/10**10, alpha=.75, figsize=[16,6]);

    for i, txt in enumerate(Top15.index):
        ax.annotate(txt, [Top15['Rank'][i], Top15['% Renewable'][i]], ha='center')

    print("This is an example of a visualization that can be created to help understand the data. \
This is a bubble chart showing % Renewable vs. Rank. The size of the bubble corresponds to the countries' \
2014 GDP, and the color corresponds to the continent.")

In [ ]:
#plot_optional() # Be sure to comment out plot_optional() before submitting the assignment!